{% set name = "polybeat" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17fc46568071985446294b703696697778954f2a8ee62577563e46a6dc3e9a68

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - setuptools
    - manim

test:
  imports:
    - polybeat
  commands:
    - python -c "from polybeat import play; play(preview=False)"

about:
  home: https://github.com/chunribu/polybeat/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A toy for visualizing polyrhythms

extra:
  recipe-maintainers:
    - chunribu
